name: PaeScape - CI (push)

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Make gradlew and build scripts executable
        shell: bash
        run: chmod +x ./gradlew && chmod +x ./build*.sh
      - run: choco install innosetup --version 6.2.2
      - run: choco install reshack --version 5.2.6
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'
      - name: build launcher
        run: ./gradlew shadowJar --console=plain
      - name: x64 installer
        shell: bash
        run: ./build-win64.sh
      - name: x86 installer
        shell: bash
        run: ./build-win32.sh
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: |
            PaeScapeSetup.exe
            PaeScapeSetup32.exe
          if-no-files-found: error
  linux:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt update
      - run: sudo apt install -y gcc-9-aarch64-linux-gnu g++-9-aarch64-linux-gnu
      - uses: actions/checkout@v3
      - name: Make gradlew and build scripts executable
        run: chmod +x ./gradlew && chmod +x ./build*.sh
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'
      - name: build launcher
        run: ./gradlew shadowJar --console=plain
      - name: linux-x64
        run: ./build-linux-x86_64.sh
      - name: linux-aarch64
        run: ./build-linux-aarch64.sh
      - uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/PaeScapeLauncher.jar
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: |
            PaeScape.AppImage
            PaeScape-aarch64.AppImage
          if-no-files-found: error